name: tests

on:
  push:
  pull_request:

jobs:
  host-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup toolchain install stable --profile minimal
      - name: Run RNG tests
        run: |
          mkdir -p build
          rustc +stable --test --edition 2021 tests/celebi_manual.rs -O -o build/celebi_manual_tests
          build/celebi_manual_tests
      - name: Run Reset and controller tests
        run: |
          rustc +stable --test --edition 2021 tests/celebi.rs -O -o build/celebi_tests
          build/celebi_tests
